const express=require("express");
const PDFDocument=require("pdfkit");
const db=require("../db/database");
const {auth,isAjeet,isOwnerAdmin,specialSeatPlannerAccess}=require("../middleware/auth");
const router=express.Router();

// Protected seating constraints stay server-side and are never returned by API/UI.
const GROUPS=[[2,3,4,5,6,9],[2,23],[3,23,6,9],[2,3,5],[2,3,4,6],[1,4],[4,16],[1,9],[1,11],[16,9]];
const pairKey=(a,b)=>a<b?`${a}:${b}`:`${b}:${a}`;
const forbidden7=new Set();for(const g of GROUPS)for(let i=0;i<g.length;i++)for(let j=i+1;j<g.length;j++)forbidden7.add(pairKey(g[i],g[j]));
function violates(a,b){if(a.classNo===7&&b.classNo===7&&forbidden7.has(pairKey(a.rollNo,b.rollNo)))return true;if(a.classNo===7&&a.rollNo===23&&b.classNo===6&&b.rollNo===2)return true;if(b.classNo===7&&b.rollNo===23&&a.classNo===6&&a.rollNo===2)return true;return false}
function setup(){return db.findAll("classes").sort((a,b)=>a.id-b.id).map(c=>{const cfg=db.findOne("seat_planner_class_configs",x=>Number(x.class_id)===Number(c.id));return {class_id:c.id,class_name:c.name,room_capacity:Number(cfg?.room_capacity||0),two_side_benches:Number(cfg?.two_side_benches||0),population:db.findAll("students",s=>Number(s.class_id)===Number(c.id)).length}})}
function slots(configs){const out=[];for(const c of configs){const max=Math.min(Number(c.roomCapacity)||0,(Number(c.twoSideBenches)||0)*2);let n=0;for(let b=1;b<=Number(c.twoSideBenches)&&n<max;b++)for(const side of ["A","B"]){if(n>=max)break;out.push({roomClassId:c.classId,roomClassName:c.className,bench:b,side});n++}}return out}
function score(group,prompt){const rolls=group.filter(s=>s.classNo===7).map(s=>s.rollNo).sort((a,b)=>a-b),p=String(prompt).toLowerCase();let score=0;if(rolls.length===3&&rolls.join(",")==="1,10,16")score-=30;if(/mix|different|separate|spread/.test(p))score-=new Set(group.map(s=>s.classNo)).size*2;if(/same class|same-class|together/.test(p))score+=new Set(group.map(s=>s.classNo)).size;return score}
function aiPlan(students,configs,prompt){const ss=slots(configs);if(students.length>ss.length)return{ok:false,error:`Configured capacity is ${ss.length}, but ${students.length} students are available. Increase classroom capacity or two-side benches.`};const bm=new Map();for(const s of ss){const k=`${s.roomClassId}:${s.bench}`;if(!bm.has(k))bm.set(k,{roomClassId:s.roomClassId,roomClassName:s.roomClassName,bench:s.bench,students:[]})}const benches=[...bm.values()];const ordered=[...students].sort((a,b)=>students.filter(x=>x!==a&&violates(a,x)).length-students.filter(x=>x!==b&&violates(b,x)).length||a.classNo-b.classNo||a.rollNo-b.rollNo);for(const s of ordered){const candidates=benches.filter(b=>b.students.length<2&&b.students.every(x=>!violates(s,x)));if(!candidates.length)return{ok:false,error:`No valid seat is available for ${s.className} Roll ${s.rollNo} with the configured classroom capacity.`};candidates.sort((a,b)=>score([...a.students,s],prompt)-score([...b.students,s],prompt)||a.students.length-b.students.length||a.bench-b.bench);candidates[0].students.push(s)}return{ok:true,benches}}
function studentRows(){return db.findAll("students").map(s=>{const c=db.findOne("classes",x=>Number(x.id)===Number(s.class_id));return{id:s.id,name:s.name,student_uid:s.student_uid,roll_no:s.roll_no,class_id:s.class_id,class_name:c?.name||""}})}

function teacherSeatGranted(req){
  if(!isAjeet(req))return false;
  return Boolean(db.findOne('seat_planner_access',x=>Number(x.teacher_id)===Number(req.user.id)&&x.enabled!==false));
}
function seatAllowed(req){return isOwnerAdmin(req)||teacherSeatGranted(req);}
router.get('/access',auth,(req,res)=>res.json({allowed:seatAllowed(req),builder:seatAllowed(req),lockedUntil:null}));
router.post('/access/grant',auth,(req,res)=>{
  if(String(req.user.uid).toLowerCase()!=='owner@principle')return res.status(403).json({error:'Only owner@principle can grant Seat Planning access.'});
  const uid=String(req.body?.teacher_uid||'').trim().toLowerCase();
  const t=db.findOne('users',u=>String(u.uid).toLowerCase()===uid&&u.role==='teacher');
  if(!t)return res.status(404).json({error:'Teacher not found.'});
  const existing=db.findOne('seat_planner_access',x=>Number(x.teacher_id)===Number(t.id));
  if(existing)db.update('seat_planner_access',x=>x.id===existing.id,{enabled:Boolean(req.body?.enabled),granted_by:req.user.id,updated_at:new Date().toISOString()});
  else db.insert('seat_planner_access',{teacher_id:t.id,enabled:Boolean(req.body?.enabled),granted_by:req.user.id});
  res.json({ok:true,enabled:Boolean(req.body?.enabled),teacher_uid:uid});
});
router.get("/class-setup",auth,(req,res)=>{if(!seatAllowed(req))return res.status(403).json({error:"Seat Planning is not available."});res.json({classes:setup()})});
router.put("/class-setup",auth,(req,res)=>{if(!seatAllowed(req))return res.status(403).json({error:"Seat Planning access is required."});const rows=Array.isArray(req.body?.classes)?req.body.classes:[];if(!rows.length)return res.status(400).json({error:"No class configuration supplied."});try{for(const x of rows){const id=Number(x.classId),cap=Number(x.roomCapacity),ben=Number(x.twoSideBenches);if(!Number.isInteger(id)||!Number.isInteger(cap)||cap<0||!Number.isInteger(ben)||ben<0||cap>ben*2)throw new Error(`${x.className||"Class"}: invalid capacity or two-side bench count.`);const old=db.findOne("seat_planner_class_configs",c=>Number(c.class_id)===id);if(old)db.update("seat_planner_class_configs",c=>c.id===old.id,{room_capacity:cap,two_side_benches:ben,updated_by:req.user.id,updated_at:new Date().toISOString()});else db.insert("seat_planner_class_configs",{class_id:id,room_capacity:cap,two_side_benches:ben,updated_by:req.user.id})}res.json({classes:setup()})}catch(e){res.status(400).json({error:e.message})}});
router.get("/students",auth,(req,res)=>{if(!seatAllowed(req))return res.status(403).json({error:"Seat Planning is not available."});res.json({students:studentRows().sort((a,b)=>(a.class_id||0)-(b.class_id||0)||(a.roll_no||999)-(b.roll_no||999))})});
router.get("/plans",auth,(req,res)=>{if(!seatAllowed(req))return res.status(403).json({error:"Seat Planning is not available."});res.json({plans:db.findAll("seat_plans").sort((a,b)=>b.id-a.id).slice(0,25)})});
router.post("/generate",auth,(req,res)=>{if(!seatAllowed(req))return res.status(403).json({error:"Seat Planning access is required."});const {title="AI Seat Plan",prompt="",classConfigs=[]}=req.body||{};const all=setup(),allowed=new Map(all.map(x=>[Number(x.class_id),x]));const configs=(Array.isArray(classConfigs)?classConfigs:[]).map(x=>({classId:Number(x.classId),className:String(x.className||""),roomCapacity:Number(x.roomCapacity),twoSideBenches:Number(x.twoSideBenches)})).filter(x=>allowed.has(x.classId));if(!configs.length)return res.status(400).json({error:"Configure at least one class capacity and two-side bench count."});const allStudents=studentRows().filter(s=>s.roll_no!=null&&configs.some(c=>c.classId===Number(s.class_id))).map(s=>({id:s.id,className:s.class_name,classNo:Number(String(s.class_name).match(/\d+/)?.[0]||0),rollNo:Number(s.roll_no),name:s.name}));if(!allStudents.length)return res.status(400).json({error:"No students with roll numbers found in the selected classes."});const result=aiPlan(allStudents,configs,String(prompt));if(!result.ok)return res.status(409).json({error:result.error});const payload={prompt:String(prompt||"").slice(0,4000),classConfigs:configs,benches:result.benches,totalCapacity:configs.reduce((n,c)=>n+Math.min(c.roomCapacity,c.twoSideBenches*2),0),studentCount:allStudents.length};const saved=db.insert("seat_plans",{title:String(title).slice(0,200),created_by:req.user.id,bench_count:result.benches.length,seats_per_bench:2,plan_json:payload,notes:String(prompt||"").slice(0,2000)});res.json({id:saved.id,created_at:saved.created_at,...payload})});
router.get("/plans/:id/pdf",auth,(req,res)=>{if(!seatAllowed(req))return res.status(403).json({error:"Seat Planning is not available."});const p=db.findOne("seat_plans",x=>Number(x.id)===Number(req.params.id));if(!p)return res.status(404).json({error:"Seat plan not found."});const doc=new PDFDocument({margin:45});res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",`attachment; filename="SFPS-Seat-Plan-${p.id}.pdf"`);doc.pipe(res);doc.fontSize(20).text("STANFORD PUBLIC SCHOOL",{align:"center"});doc.fontSize(15).text("AI Seat Planning Report",{align:"center"});doc.fontSize(10).text(`${p.title} • ${new Date(p.created_at).toLocaleString()}`,{align:"center"});doc.moveDown();for(const b of p.plan_json.benches){doc.fontSize(12).text(`${b.roomClassName} · Bench ${b.bench}`,{underline:true});for(const s of b.students)doc.fontSize(9).text(`• ${s.name} — Class ${s.classNo}, Roll ${s.rollNo}`);doc.moveDown(.4)}doc.end()});
router.post("/chat",auth,(req,res)=>{if(!isAjeet(req)&&!isOwnerAdmin(req))return res.status(403).json({error:"Seat Planning assistant access is restricted."});const message=String(req.body?.message||"").trim();if(!message)return res.status(400).json({error:"Enter a message."});res.json({reply:"Tell me the seating goal, class selection, or arrangement preference. I will use the configured classroom capacity, two-side benches, student population and roll data to build the plan."})});
module.exports=router;
